### ISSUE TITLE
POST example

### ISSUE THREAD

**Issue by sull** [TheCodingCompany/MastodonOAuthPHP#6]
Can this been used to post/toot status updates too?

**Comment by digitalhuman** [comment]
Not yet but I will fix that tomorrow. Well, that was/is the plan :) lol

**Comment by sull** [comment]
cool. do you know anything about why this doorkeeper related redirect_uri error happens?

> The redirect uri included is not valid.

**Comment by digitalhuman** [comment]
No i have no idea. I experienced it also a few times. Could be session related i might say.
